ALTER TABLE students ADD COLUMN ID_STUDENTS INT AUTO_INCREMENT PRIMARY KEY;
SELECT * FROM students;
SHOW TABLES; 
SHOW TABLES ;
DESCRIBE students;

ALTER TABLE students RENAME COLUMN ID TO UNIQUE_ID;
ALTER TABLE students DROP COLUMN  UNIQUE_ID;


